services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Inquiry\:
    resource: '../Classes/*'

  WapplerSystems\Inquiry\Form\Factory\InquiryFormFactory:
    public: true

  WapplerSystems\Inquiry\Form\Factory\QuickInquiryFormFactory:
    public: true
